filter:
    excluded_paths:
        - Tests/*
        - vendor/*
        - Features/*
build:
    dependencies:
        before:
            -
                command: 'composer install'
checks:
    php: true
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    tests:
        override:
            - phpcs-run