filter:
    excluded_paths:
        - Tests/*
        - vendor/*
        - Features/*
build:
    dependencies:
        before:
            -
                command: 'composer install'
checks:
    php: true
build:
    environment:
        php:
            version: 7.1
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover=coverage.clover Tests/Units'
                coverage:
                    file: 'coverage-clover'
                    format: 'clover'
