build:
    dependencies:
        before:
            - 'composer install'
build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            - 'vendor/bin/phpunit --bootstrap vendor/autoload.php Tests/Units'