filter:
    excluded_paths:
        - Tests/*
        - vendor/*
        - Features/*
checks:
    php: true
build:
    environment:
        php:
            version: 7.1
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
        tests_node:
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'
                        coverage:
                            file: 'coverage-clover'
                            format: 'clover'